name: habitit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  cloud_firestore: ^5.6.3
  connectivity_plus: ^6.1.3
  dartz: ^0.10.1
  equatable: ^2.0.7
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  firebase_core_platform_interface: ^5.4.0
  firebase_messaging: ^15.2.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  font_awesome_flutter: ^10.8.0
  google_sign_in: ^6.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  internet_connection_checker: ^3.0.1
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5

flutter:
  uses-material-design: true
