name: habitit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  cloud_firestore: ^5.6.3
  dartz: ^0.10.1
  equatable: ^2.0.7
  firebase_auth: ^5.4.2
  firebase_messaging: ^15.2.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5

flutter:
  uses-material-design: true
