// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeL6_7zZrr_KjKgq9pxV8xcGtNOJiSYV8',
    appId: '1:447620558965:web:cbf5e47aa5882da2ef483c',
    messagingSenderId: '447620558965',
    projectId: 'habitit-ef892',
    authDomain: 'habitit-ef892.firebaseapp.com',
    storageBucket: 'habitit-ef892.firebasestorage.app',
    measurementId: 'G-V9N6Y4P7RQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcF01jAVrkOou2tUW-Dlsnp125mcgL-gc',
    appId: '1:447620558965:android:5aabb26330a5d77fef483c',
    messagingSenderId: '447620558965',
    projectId: 'habitit-ef892',
    storageBucket: 'habitit-ef892.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjnGPYT5jDzODSUoasfwpnzZ3FbNy1lqQ',
    appId: '1:447620558965:ios:ba7a1c001a74de6fef483c',
    messagingSenderId: '447620558965',
    projectId: 'habitit-ef892',
    storageBucket: 'habitit-ef892.firebasestorage.app',
    androidClientId: '447620558965-lun6omgfel93rjp9ohmbcl2tufqdhalh.apps.googleusercontent.com',
    iosClientId: '447620558965-4chho0g6faoq6a1cqcj85s39hr97u2bd.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjnGPYT5jDzODSUoasfwpnzZ3FbNy1lqQ',
    appId: '1:447620558965:ios:ba7a1c001a74de6fef483c',
    messagingSenderId: '447620558965',
    projectId: 'habitit-ef892',
    storageBucket: 'habitit-ef892.firebasestorage.app',
    androidClientId: '447620558965-lun6omgfel93rjp9ohmbcl2tufqdhalh.apps.googleusercontent.com',
    iosClientId: '447620558965-4chho0g6faoq6a1cqcj85s39hr97u2bd.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeL6_7zZrr_KjKgq9pxV8xcGtNOJiSYV8',
    appId: '1:447620558965:web:a6654f937453e953ef483c',
    messagingSenderId: '447620558965',
    projectId: 'habitit-ef892',
    authDomain: 'habitit-ef892.firebaseapp.com',
    storageBucket: 'habitit-ef892.firebasestorage.app',
    measurementId: 'G-2P5QV9HVF3',
  );

}