name: Deploy Flutter Web & APK

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  check-readme-update:
    runs-on: ubuntu-latest
    outputs:
      skip_ci: ${{ steps.check.outputs.skip_ci }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Check if README.md is the only file changed
        run: |
          # Use the commit range from the push event
          git diff --name-only "${{ github.event.before }}" "${{ github.event.after }}" > changed_files.txt
          echo "Changed files:"
          cat changed_files.txt

          # If any file other than README.md is found, run CI.
          if grep -qv '^README.md$' changed_files.txt; then
            echo "Files other than README.md changed, running CI."
            echo "skip_ci=false" >> $GITHUB_ENV
          else
            echo "Only README.md changed, skipping CI."
            echo "skip_ci=true" >> $GITHUB_ENV
          fi
  
  test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest
    needs: check-readme-update
    if: needs.check-readme-update.outputs.skip_ci == 'false'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.4" 

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test

  build-apk:
    name: Build APK
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.4"

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK (Unsigned)
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

  deploy-web:
    name: Deploy Flutter Web to Firebase
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.4"

      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools
          firebase --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  
  update-readme:
    name: Update README with Deployment Links
    runs-on: ubuntu-latest
    needs: [deploy-web, build-apk]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update README
        run: |
          WEB_URL="https://habitit-ef892.web.app/"
          APK_URL="https://github.com/conykay/habitit/actions/runs/${{ github.run_id }}/artifacts/2654119751"
          sed -i "s|\(\*\*Web App:\*\* \).*|\1[Habitit Web]($WEB_URL)|" README.md
          sed -i "s|\(\*\*Latest APK:\*\* \).*|\1[Habitit App]($APK_URL)|" README.md
      
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m "Update README with latest deployment links [skip ci]" || echo "No changes to commit"
          git push origin production || echo "No changes to push"
