name: Deploy Flutter Web & APK

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  check-readme-update:
    runs-on: ubuntu-latest
    outputs:
      skip_ci: ${{ steps.check.outputs.skip_ci }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if README.md is the only file changed
        id: check
        run: |
          # Use the commit range from the push event
          git diff --name-only "${{ github.event.before }}" "${{ github.event.after }}" > changed_files.txt
          echo "Changed files:"
          cat changed_files.txt

          # If any file other than README.md is found, run CI.
          if grep -qv '^README.md$' changed_files.txt; then
            echo "Files other than README.md changed, running CI."
            echo "::set-output name=skip_ci::false"
          else
            echo "Only README.md changed, skipping CI."
            echo "::set-output name=skip_ci::true"
          fi

  test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest
    needs: check-readme-update
    if: needs.check-readme-update.outputs.skip_ci == 'false'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.4"

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test

  build-apk:
    name: Build APK
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.4"

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK (Unsigned)
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

  deploy-web:
    name: Deploy Flutter Web to Firebase
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3
